language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: true
node_js:
- lts/*
install: npm install
jobs:
  include:
  - stage: test
    script:
    - npm run build
    - npm run lint
    - npm run test
    - npm run is-es5
    after_success: npm run codecov
  - stage: deploy
    if: branch = master
    script: npm run deploy
env:
  global:
  - secure: SqzIpYGvVdC174w4S692dm2qdXgjkiwTLFQ/PgoRtqoNtP2F1ff/6KZG/9PtSP6H7gJVaPT/brO34LksG1/eiKFRMOI/AK6GjNvFG+NoFsbJ/A8RI1QPd9McbyTXv0c1/fM2dWdUo+Hgpv8kF/xFmFyKPKGQVDf7m9IDDl3o2D8s6YcM8A5k+5Pd0YD4mz0+B3H+BhroPPgXxbraC1f1o0oxVFGnHMx8B0DtSLooCH7Rq8dQ5+bBWrkwdXfngYeakuPTfKYSQxZE5FBSyayrPlrGg5VMoZw40I4dwfXVisuiVbREMxHcgQ6bjpI+erNO3KjpgQIZtMoioPFQMCnv3Z99fooBtORshD8EONXTBH/Hv5MSx5nwXTfaxSmSwpOIWTAV3MA+cw0zsV/+dC/TwDJrX58f0EwInMm+7LyqYlFgTTQl4YmYdzOzdJ3ZPrxBwcUzh8rodYcWC0Tshx2sBnNaBxBQk9v1oq4BgajcJpSRwLpeDlBs/i898SAvhetg0fDm6lwtPelUdrspwSfqOIk2o4PpiJTkC5JMd7KDJzla0OC35/PFIPsjIZ43DSH6OBzAK9x60EqekoQAOAzb5OgaUxp8Sc7mxo0Weerms6hc7kJXYK+jqRInqUEl9A+M0QfoB6hXkCUgAo+GfYpzNQfkoR0uHV6wuk97Xn4SZ4g=
  - secure: eLSq0K4x7ZmwTO8eqgO2Ob7saY3B45bL0wUeROiRigaGaMJiSAsQXGd2ArdzDE0sCfuTu2MlBt2vkPWRvZIdHG80LNZzhYS1dIfzcyO+jHkfN6YMD4g6s+mtBBSx3B0NT4swFhXGFKGNOzC9ylTYDa2WxVLZwzIWEDjCpp7yFnWmQKRip8DPMPo+WDc/sP8k44kqAJnd54cQaqaXm5jqyau5vTK1+PXpX4kLmulryUrVLt/Jd6prbsLq6LSiDaz2XRnwlnLj1JwLnyZ2YkcspszGm2YQd0fo2QvmBLx1rCkwL9eP/sX8ej69sKCI4J+EFNqC8j5C0A51aoez/KBInkVR0qRCZSGCJVnicGTZbEdQNuBmsqCIHZdhOoBPR1uBqKy2IcTy/NgIcyJgTm9faMpUNoZJnTp1KaYq9+UYExLGfLv7pmu47n20Pq9f1EHgW3/rBqfvZlhDlGWJ7UI1akh4erEzT7+dWWvvOoqL9deSxuRR8XHAYxyjxMhxjyr3zP14zC+ofulu8WxgI9XH9fZshZMz0ehMxUCGmxYw8Z18oDqqopXcKVdB40WgGDcis3UcYaBXlAZTacOjAEPhIZ63hz6xEtaLM982Z66JSICF6onpfGsIrhdjIwlFfIb72jQxuJVN9lmwu6BJg1X4wxnNZhXHQFcjrG17s+mPXus=
  - secure: FdHprhZswjxxjKHVPFb9e/+ETBX0bTmDUfC71NjTor7iA+jofvVcCLRtB+sEhBh3D/s3bMRfx9wVmFv7TJuraPEjB14sRqbdvQjcmgEyvezO/i+PokpLmHdBbvK0r3/fYZ5+v99LEo2RNmPkP5Atfmm4qmPS4AsS+C52NIuR4gCn5+exHdzJbnoNVbVDAQTLUiO8rVeSqytByQKWQqVDRs+m+wtxF0POPdBAYCrVLXA9gLElQTq1Yk8vnQY6IrT0Skt825HnJBP9s1CY+cp9KuK9pSAM0XF7phlIpQP4Y7/nnHU7glJuGoRuFwOQpEfWOantX5N7dfaXtgsiAe149w6k3TQNmEt+hR//1Fb4qh7XxV8eOb/JtqjIBr5GTmuv+W+n91yCvV01jQKlLSnExJc/iklGCUNxXnEBwnzp1qeGHK3NpIV8JW5YaGcuAdLePXJvx3tc2jNuGb+IGrp6ug8m+2akjps85PVo5j092NSo7Exf3ZRe5AGxm3RSRvMFn0eZyTvHnPfokMLHtX6YwPyG8XFGjfZ0/gNzfooKxg0hdPW2k+ct1JJe6UtRFrbInLes1lFNz/aUNp1sBj1upRRjeCZdQMbAEmGObMWcaUmpaSPgU6wFA5matkYOU+YInMkTNHfak73U3cEq6dBWgncao3KmsF2Eo4DRxPkwvuw=
  - secure: YScyeFEKr6iOB/vuNWE+gPEAraed6JgtImMeVK3UdFdKDx4ZNSofR/OvyhqeXjP+jXzbdYpYQkdn8lw0nLuxSh54+b5bZ/BFywzUPAmsitmMZaxLgmWveN0SOMlQDdMnYMW0c6H61yvko1rMralYBoLd2sHbclroOftd54V3HPn8GbhjN6o8t/wmCi3lPDzggiEKKAXt49a2cHgiEKXvRTaZ/KtzfJGHVqs3nP+RJdKxA9xxvkannRmZMMjIerQDQbXT+19pQNigtFhdFjZXZIGzUq7Dt0OrHz3GYs1WLkaxNPy+FmKuXt/o/y+L8aVu0nqs7uN0KPQGW59/d55Sma80k1XwhSpu6Wg2OJVEp+r9uJHjxZAJSz4RBRY/uvfMCjQnvrbRfRkACo0F9oMc2BbqGa2mLdTJDecIpcEAByiXVP38PEcqZJb5GHFFngO+/vdCR3jj+2xEnTJRFELfQLmOi9ENNzb8gu2Z4eh+1KsUTYF46i2TZaljOU8jQUFtjmgoKfm35mxz38oTWcTCb0ZWWDXN09P/o4TkXniytbY1EXpiwfmjq+4PF69oBiwKbCah+GUW+s8Z1fG4vbvWBR9PuNNYaPP/rceN8L6rKNx8BW3Jx9sEa16GYIyNQhHpFPtTIF/uH+AI1Ck8poSJ7ZclsfQ2efxiKk5Wi6pNy4U=
